<?php
/**
 * Created by PhpStorm.
 * User: ggrenuy
 * Date: 10.05.15
 * Time: 17:31
 */

function round2_menu () {
    $items['round2'] = array(
        'title' => 'Round 2 theme function',
        'page callback' => 'round2_example',
        'access callback' => TRUE,
    );
    return $items;
}

function round2_form ($form, &$form_state) {
  $form['round2'] = array(
    '#type' => 'select',
    '#title' => t('Select'),
    '#options' => array(
        1 => t('First'),
        2 => t('Second'),
        3 => t('Third'),
    ),
    '#default_value' => 1,
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Send',
  );
  return $form;
}

function round2_theme() {
    return array(
        'round2' => array(
            'variables' => array(),
        ),
        'round2_tpl' => array(
            'template' => 'round2',
            'list' => '',
        ),
    );
}

function theme_round2($variables) {

    $output = drupal_get_form('round2_form');
    $output = render($output);

    return $output;
}

/**
 * @return string
 */
function round2_example() {
    $round2['#id'] = 'round_2';
    $round2['#options'] = array('first element', 'second element', 'thirt element');
    $round2['attributes'] = array();

    $ret = theme('round2', $round2);


    return theme('round2_tpl', array( 'list' => $ret));
}
